spring:
  application:
    name: ff-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*" #Set the list of headers that a pre-flight request can list as allowed for use during an actual request.
            allowCredentials: true #是否允许cookie随请求发送
            maxAge: 1800
            #- POST
      default-filters: #--里面可以定义一些共同的filter，对所有路由都起作用
        - TokenCheck # TokenCheck+GatewayFilterFactory的类，即TokenCheckGatewayFilterFactory
        - UrlAcessControl
        - name : Hystrix
          args: 
            name: authHystrixCommand #- 在方法上加注解 @HystrixCommand(commandKey="authHystrixCommand")
            fallbackUri: forward:/hystrixTimeout
        - name : Retry
          args:
            retries: 1
                      
server:
  port: 8888
  http2:
    enabled: true
  #servlet:
    #context-path: /api #--Finchley版本context-path不起作用，加这个是便于前置nginx根据路径转发
eureka:
  instance:
    prefer-ip-address: true
    #status-page-url-path: /actuator/info
    #health-check-url-path: /actuator/health
  client: 
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/  #http://114.115.207.28:8081/eureka/
    register-with-eureka: false # 不作为Eureka服务注册   
      
hystrix:
  #threadpool:
    #default:
      #maximumSize: 400 #此属性设置最大线程池大小。 这是在不开始拒绝HystrixCommands的情况下可以支持的最大并发数。 请注意，此设置仅在您还设置allowMaximumSizeToDivergeFromCoreSize时才会生效。
      #allowMaximumSizeToDivergeFromCoreSize: true #此属性允许maximumSize的配置生效。 那么该值可以等于或高于coreSize。 设置coreSize <maximumSize会创建一个线程池，该线程池可以支持maximumSize并发，但在相对不活动期间将向系统返回线程。
  command: 
    authHystrixCommand: #--对应Hystrix里args的name，默认是"default"
      execution:
        isolation: 
          thread:
            timeoutInMilliseconds: 5000 #设置熔断路由的超时时间

app: 
  token:
    headerName: accessToken # token在header里面的name
    userInfoHeader: userInfo #重新构建请求时，将用户信息加到请求头里的headname
    cache:
      initialCapacity: 500 #token缓存初始大小
      maximumSize: 100000 #token缓存的最大大小
      expireAfterAccessWithMinutes: 30 #最后一次访问后间隔多少分钟失效
    ingoreTokenUrls: /api/auth/login, /api/auth/getToken, /websocket/course/ #忽略检查token的URL
    publicKey: FF79@34$123de
    userInfoKey: userInfo #token里面的用户信息键值
    
      
    
      