spring:
  profiles:
    active:
      dev
  application:
    name: ffadmin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ff?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    databaseplatform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  cloud:
    loadbalancer:
      retry:
        enabled: false
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/


feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: false
  client:
      config:
        default:
          connectTimeout: 1000
          readTimeout: 1000
          loggerLevel: full

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000


ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
  # 对所有操作都进行重试（ConnectTimeout和ReadTimeout都重试）
  OkToRetryOnAllOperations: false
  # 对当前实例重试次数
  MaxAutoRetries: 0
  # 对下一个实例重试的次数
  MaxAutoRetriesNextServer: 0
  restclient:
    enabled: true

custom:
  swagger:
    enable: true #是否启用swagger文档
  log:
    path: E:/logback/${spring.application.name}/${spring.profiles.active}
  token:
    prefix: token_val_
    claim: userModel
    secret: FF79@34$123de
    longTime: 30
    alg: HS512
    survival: 360000
  admin:
    prefix: token_val_
    longTime: 30
    pwd: 111111
    inviteLink: http://m.newplay.me/login
    codeWidth: 300
    codeHeight: 300
    picFormat: jpg
    picSavePath: F://codeImg
  entrust:
    prefix: entrust_val_
    entrustBusiness:  买卖
    entrustCancel:  已撤
    entrustCancelBuy: 买入
    entrustCancelSell: 卖出
  deal:
    prefix: deal_val_
    dealBuy: 买入
    dealSell: 卖出
  urlKey:
    searchKey: url_val_search
    roleKey: role_
  system:
    sdformat: yyyyMMdd-HH:mm:ss
    hms: -00:00:00
    autoBuy: autoBuy
    shangRegex:  ^(60)|(900)[0-9]*$
    shenRegex:  ^(000)|(002)|(300)|(200)[0-9]*$
    chuangRegex:  ^3[0-9]*$
  pay:
    url: http://test.rongxintong.com:9259/rxtCashierDeskWebservice/gateway/
    reciveWay: gatewayCheckstandPay
    weChatOrAilpay: appPayPublic
    queryPayResult: queryPayResult
    queryReconTrans: queryReconTrans
    QRcode: gatewayPayByQRcode
  risk:
    maxBuyOne: 0.8
    venturEditionMax: 0.5
    holdOverFiveAvg: 0.3
    holdOverCurrency: 1000000.0
    stockShutDown: 1
  scheduled:
    entrust:  0,30 0/1 9,10,11,12,13,14,15 * * ?
    deal: 15,45 0/1 9,10,11,12,13,14,15 * * ?
    fiveAvg:  0 30 15 * * 1,2,3,4,5
    everyDay: 0 30 20 * * ?
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

