spring:
  profiles:
    active:
      dev
  application:
    name: ffexchange
  datasource:
      databaseplatform: org.hibernate.dialect.MySQL5InnoDBDialect
      url: jdbc:mysql://127.0.0.1:3306/ff?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
      username: root
      password: root
  jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
  cloud:
      loadbalancer:
        retry:
          enabled: false
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/

feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ffexchange:
      ribbon:
        ConnectTimeout: 5000
        ReadTimeout: 5000
        # 对所有操作都进行重试（ConnectTimeout和ReadTimeout都重试）
        OkToRetryOnAllOperations: false
        # 对当前实例重试次数
        MaxAutoRetries: 0
        # 对下一个实例重试的次数
        MaxAutoRetriesNextServer: 0
        restclient:
          enabled: true

custom: 
  swagger:
    enable: true #是否启用swagger文档
  log: 
    path: E:/logback/${spring.application.name}/${spring.profiles.active}