spring:
  profiles:
    active:
      dev
  application:
    name: ffexchange
  datasource:
      databaseplatform: org.hibernate.dialect.MySQL5InnoDBDialect
      url: jdbc:mysql://127.0.0.1:3306/ff?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
      username: root
      password: root
  jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/

custom: 
  swagger:
    enable: true #是否启用swagger文档
  log: 
    path: E:/logback/${spring.application.name}/${spring.profiles.active}